mybatis:
  type-aliases-package: com.wc.wcnj.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jeesite
    url: jdbc:mysql://127.0.0.1:3306/jeesite?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: jeesite
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
